---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    engine: fluentd
    version: 1.1.0
spec:
  selector:
    matchLabels:
      name: splunk-kubernetes-metrics
      version: 1.1.0
  template:
    metadata:
      name: splunk-kubernetes-metrics
      labels:
        name: splunk-kubernetes-metrics
        app: splunk-kubernetes-metrics
        engine: fluentd
        version: 1.1.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: splunk-kubernetes-metrics
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: splunk-fluentd-k8s-metrics
        image: splunk/k8s-metrics:1.1.0
        imagePullPolicy: Always
        env:
        - name: SPLUNK_HEC_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-metrics
              key: splunk_hec_token
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 300Mi
        volumeMounts:
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      volumes:
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-metrics
      - name: secrets
        secret:
          secretName: splunk-kubernetes-metrics
